### ISSUE TITLE
Error gramático

### ISSUE THREAD

**Issue by clavit4** [insidesecurity-factory/insidesecurity.cl#14]
old: traves
new: través
https://github.com/insidesecurity-factory/insidesecurity.cl/blob/e2a60ae6c3175b8b05e6ed477b5d473f73c7f2b0/src/layout/index.js#LL135C5-L135C57

**Comment by yhojann-cl** [comment]
Corregido en 21a255e0a87ebaaa449d053b5a89d8b6da41b42c
