### ISSUE TITLE
Idea: Crear enlace que invita a trabajar con nosotros

### ISSUE THREAD

**Issue by yhojann-cl** [insidesecurity-factory/insidesecurity.cl#16]
### ¿Cual es la idea que propone?

Se debe crear una sección o enlace que invite a las personas a trabajar en Insidesecurity. Preferentemente una sección nueva con una imagen bonita y un mensaje bien descriptivo, un texto que indique los beneficios, etc.

### ¿Qué soluciona o cual es el beneficio?

Ayuda al proceso de reclutamiento de Insidesecurity.

**Comment by cintyaviv20** [comment]
Se estará trabajando en la sección "Trabajar con nosotros" después de definir nuevo diseño de la página web, se está dando seguimiento a ese issue.

**Comment by cintyaviv20** [comment]
Resuelto en PR https://github.com/insidesecurity-factory/insidesecurity.cl/pull/20 en commit https://github.com/insidesecurity-factory/insidesecurity.cl/pull/20/commits/f6fbada765b1047c9999eadbe64e81ab3a1adebc
